### PR TITLE
WIP dockerize development workflow

### PR DESCRIPTION
**Pull request by NdagiStanley**
#### What does this PR do?
Adds dockerfile, docker-compose.yml to add docker to the developer workflow
#### How should this be manually tested?
Run `docker-compose up`

### CODE REVIEW

**Comment by meshulam** [comment]
Great meeting you today Stanley! I'll pull this down and try to get past the migration errors in the next couple days.

**Comment by NdagiStanley** [comment]
Same here. Nice to have met you yesterday.
Wonderful.

**Comment by meshulam** [comment]
Thinking about this more, I think there are actually two separate docker use cases:

1. Local development: Use dockerized postgres for easy/cross platform setup, but still run the core app normally. Python developers should be comfortable getting a virtualenv set up, and even if we mounted the code as a volume in the container, there would be situations where people would need to remember to rebuild the app's docker image. I don't think we really get much by running python inside docker, and it makes some things harder.

2. Production deployment: Maybe Dockerize the app, using remote postgres.

With #62 and the default postgres docker image we're pretty close to addressing local development. I'm gonna see what configuration looks like for that, I might pull your docker-compose into another PR and leave this PR open for the production use case.

**Comment by NdagiStanley** [comment]
This makes sense. I am totally up for this approach.

**Comment by NdagiStanley** [comment]
This PR is probably outdated.
Closing this now.

**Pull request closed without merging**
